### ISSUE TITLE
DOSBox: consider SDL2 patches

### ISSUE THREAD

**Issue by bam80** [Pixelnarium/flatpak#1]
SDL2 patches are already there, maybe a good candidates to try with your DOSBox:
https://www.vogons.org/viewtopic.php?f=41&t=34770

**Comment by Pixelnarium** [comment]
What are the main benefits in this other than that it uses SDL2? I main reason why I don't use the DOSBox from flathub is that I want to have Glide and SDL_sound support. Other than that I want to keep it as close to upstream as possible.

**Comment by bam80** [comment]
The main reason is that SDL1 abandoned long time ago. Recent SDL_sound don't support it any more. If you don't see benefits of SDL2 patches, I think we can close the issue

**Comment by Pixelnarium** [comment]
Yeah, just for the sake of being "more modern" and maybe problems I am not in the mood to maintain a flatpak manifest for that sorry.
