### ISSUE TITLE
Dependency when installing duckstation

### ISSUE THREAD

**Issue by VaGNaroK** [Pixelnarium/flatpak#3]
when installing the flatpak-builder package and following with the command (`flatpak-builder --user --install build <jsonfile>`), a kde dependency problem appears and the process is interrupted as shown below:

vagnarok@vagnarok-PC:~/Área de Trabalho/flatpak-master/org.duckstation.DuckStati
on$ flatpak-builder --user --install build org.duckstation.DuckStation.json 
error: org.kde.Sdk/x86_64/5.15 not installed
Failed to init: Unable to find sdk org.kde.Sdk version 5.15

how can i install this dependency to install flatpak?

has a file in python that should be used to compile files from repositories (I think that's it, I'm very new to the subject), and when running the following error appears.

vagnarok@vagnarok-PC:~/Área de Trabalho/flatpak-master$ python3 ./build.py 
Traceback (most recent call last):
  File "./build.py", line 73, in <module>
    main()
  File "./build.py", line 36, in main
    repo_path = sys.argv[1]
IndexError: list index out of range

**Comment by Pixelnarium** [comment]
Try `flatpak install org.kde.Sdk` and then choosing the right SDK version.

**Comment by Pixelnarium** [comment]
Also on flathub from someone else: https://flathub.org/apps/details/org.duckstation.DuckStation
